packages:
  api: !include /config/common/api.yaml
  binary_sensor: !include /config/common/binary_sensor.yaml
  captive_portal: !include /config/common/captive_portal.yaml
  esp32: !include /config/common/esp32.yaml
  esphome: !include /config/common/esphome.yaml
  logger: !include /config/common/logger.yaml
  ota: !include /config/common/ota.yaml
  sensor: !include /config/common/sensor.yaml
  switch: !include /config/common/switch.yaml
  text_sensor: !include /config/common/text_sensor.yaml
  time: !include /config/common/time.yaml
  web_server: !include /config/common/web_server.yaml
  wifi: !include /config/common/wifi.yaml

esphome:
  friendly_name: ${device}
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio

esp32_camera:
  id: espcam
  name: Camera
  external_clock:
    pin: 10
    frequency: 20MHz
  i2c_id: bus_a
  data_pins:
    - 15
    - 17
    - 18
    - 16
    - 14
    - 12
    - 11
    - 48
  vsync_pin:
    number: 38
  href_pin:
    number: 47
  pixel_clock_pin:
    number: 13
  #resolution: 800x600

i2c:
  sda:
    number: 40
  scl:
    number: 39
  id: bus_a

psram:
  mode: octal
  speed: 80MHz

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot
