packages:
  api: !include /config/common/api.yaml
  captive_portal: !include /config/common/captive_portal.yaml
  esp32: !include /config/common/esp32.yaml
  esphome: !include /config/common/esphome.yaml
  logger: !include /config/common/logger.yaml
  ota: !include /config/common/ota.yaml
  sensor: !include /config/common/sensor.yaml
  switch: !include /config/common/switch.yaml
  text_sensor: !include /config/common/text_sensor.yaml
  time: !include /config/common/time.yaml
  web_server: !include /config/common/web_server.yaml
  wifi: !include /config/common/wifi.yaml
  
esphome:
  friendly_name: ${device}
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio

esp32_camera:
  id: espcam
  name: Camera
  external_clock:
    pin: GPIO10
    frequency: 20MHz
  i2c_id: bus_a
  data_pins: [GPIO15, GPIO17, GPIO18, GPIO16, GPIO14, GPIO12, GPIO11, GPIO48]
  vsync_pin: GPIO38
  href_pin: GPIO47
  pixel_clock_pin: GPIO13
  #resolution: 800x600

i2c:
  sda: GPIO40
  scl: GPIO39
  id: bus_a
  
psram:
  mode: octal
  speed: 80MHz
  
esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot
