esphome:
  name: ${devicename}
  area: ${room}

esp8266:
  board: esp01_1m

packages:
  api: !include /config/common/api.yaml
  captive_portal: !include /config/common/captive_portal.yaml
  logger: !include /config/common/logger.yaml
  ota: !include /config/common/ota.yaml
  sensor: !include /config/common/sensor.yaml
  switch: !include /config/common/switch.yaml
  text_sensor: !include /config/common/text_sensor.yaml
  time: !include /config/common/time.yaml
  web_server: !include /config/common/web_server.yaml
  wifi: !include /config/common/wifi.yaml

globals:
  - id: channel1_last_state
    type: int
    restore_value: no
    initial_value: '2'

switch:
  - platform: gpio
    name: ${channel_1}
    pin: GPIO4
    id: relay1
    icon: ${icon1}
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: ${channel_2}
    pin: GPIO15
    id: relay2
    icon: ${icon2}
    restore_mode: ALWAYS_ON

i2c:
  sda: GPIO12
  scl: GPIO14

sensor:
  - platform: ade7953_i2c
    irq_pin: GPIO16
    update_interval: ${update_interval}
    voltage:
      name: Voltage
    current_a:
      name: ${channel_1} Current
    current_b:
      name: ${channel_2} Current
    active_power_a:
      name: ${channel_1} Power
      id: power_channel_1
      filters:
        - multiply: -1
        - lambda: |-
            if (x >= 0) return x;
            else x=0; return x;
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: relay1
    active_power_b:
      name: ${channel_2} Power
      id: power_channel_2
      filters:
        - multiply: -1
        - lambda: |-
            if (x >= 0) return x;
            else x=0; return x;
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: relay2
  - platform: total_daily_energy
    name: ${channel_1} Energy
    power_id: power_channel_1
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
  - platform: total_daily_energy
    name: ${channel_2} Energy
    power_id: power_channel_2
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
  - platform: ntc
    sensor: temp_resistance_reading
    name: Temp
    unit_of_measurement: "Â°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
          - switch.turn_off: relay2
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0
    update_interval: ${update_interval}

status_led:
  pin:
    number: GPIO0
    inverted: yes

text_sensor:
  - platform: homeassistant
    id: ha_input_text_channel1
    entity_id: input_boolean.${automation_name}

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
    id: ${channel_1}_input
    filters:
      - delayed_on_off: 50ms
    on_state:
      then:
        - if:
            condition:
              lambda: 'return id(channel1_last_state) == 2;'
            then:
              - lambda: 'id(channel1_last_state) = id(${channel_1}_input).state ? 1 : 0;'
              - delay: 400ms
              - if:
                  condition:
                    lambda: 'return (id(${channel_1}_input).state ? 1 : 0) == id(channel1_last_state);'
                  then:
                    - logger.log: ${channel_1} Single-Click Detected
                    - switch.toggle: relay1
                  else:
                    - if:
                        condition:
                          lambda: 'return id(ha_input_text_channel1).state == "on";'
                        then:
                          - logger.log: ${channel_1} Double-Click Detected
                          - homeassistant.service:
                              service: input_boolean.turn_off
                              data:
                                entity_id: input_boolean.${automation_name}
                        else:
              - homeassistant.service:
                              service: input_boolean.turn_on
                  data:
                                entity_id: input_boolean.${automation_name}
              - lambda: 'id(channel1_last_state) = 2;'

  - platform: gpio
    pin:
      number: GPIO5
    id: ${channel_2}_input
    filters:
      - delayed_off: 3s
