esphome:
  name: ${devicename}
  area: ${room}

esp32:
  board: esp32doit-devkit-v1

packages:
  api: !include /config/common/api.yaml
  esp32_ble_tracker: !include /config/common/esp32_ble_tracker.yaml
  captive_portal: !include /config/common/captive_portal.yaml
  logger: !include /config/common/logger.yaml
  ota: !include /config/common/ota.yaml
  sensor: !include /config/common/sensor.yaml
  switch: !include /config/common/switch.yaml
  text_sensor: !include /config/common/text_sensor.yaml
  time: !include /config/common/time.yaml
  #web_server: !include /config/common/web_server.yaml
  wifi: !include /config/common/wifi.yaml

switch:
  - platform: gpio
    name: ${channel_1}
    pin: GPIO13
    id: light
    icon: ${icon1}
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: ${channel_2}
    pin: GPIO12
    id: fan
    icon: ${icon2}
    restore_mode: ALWAYS_ON

i2c:
  sda: GPIO26
  scl: GPIO25

sensor:
  - platform: ade7953_i2c
    irq_pin: GPIO27
    update_interval: ${update_interval}
    voltage:
      name: Voltage
    current_a:
      name: ${channel_1} Current
    current_b:
      name: ${channel_2} Current
    active_power_a:
      name: ${channel_1} Power
      id: power_channel_1
      filters:
        - multiply: -1
        - lambda: |-
            if (x >= 0) return x;
            else x=0; return x;
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: light
    active_power_b:
      name: ${channel_2} Power
      id: power_channel_2
      filters:
        - multiply: -1
        - lambda: |-
            if (x >= 0) return x;
            else x=0; return x;
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: fan
  - platform: total_daily_energy
    name: ${channel_1} Energy
    power_id: power_channel_1
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
  - platform: total_daily_energy
    name: ${channel_2} Energy
    power_id: power_channel_2
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
  - platform: ntc
    sensor: temp_resistance_reading
    name: Temp
    unit_of_measurement: "Â°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
          - switch.turn_off: fan
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: adc
    id: temp_analog_reading
    pin: GPIO35
    update_interval: ${update_interval}

status_led:
  pin:
    number: GPIO0
    inverted: yes

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    id: ${channel_1}_input
    on_state:
      then:
        - logger.log: Single-Click Detected
        - if:
            condition:
              api.connected:
            then:
                          - homeassistant.service:
                  service: light.toggle
                              data:
                    entity_id: light.${light_group}
  - platform: gpio
    pin:
      number: GPIO18
    id: ${channel_2}_input
    filters:
      - delayed_off: 3s
