packages:
  api: !include /config/common/api.yaml
  captive_portal: !include /config/common/captive_portal.yaml
  esp8266: !include /config/common/esp8266.yaml
  esphome: !include /config/common/esphome.yaml
  logger: !include /config/common/logger.yaml
  ota: !include /config/common/ota.yaml
  sensor: !include /config/common/sensor.yaml
  switch: !include /config/common/switch.yaml
  text_sensor: !include /config/common/text_sensor.yaml
  time: !include /config/common/time.yaml
  web_server: !include /config/common/web_server.yaml
  wifi: !include /config/common/wifi.yaml

logger:
  baud_rate: 0

status_led:
  pin:
    number: 13

uart:
  rx_pin:
    number: RX
  baud_rate: 4800
  parity: EVEN

switch:
  - platform: gpio
    pin:
      number: 12
    id: relay1
    name: Relay
    icon: ${icon}
    restore_mode: ${restore}

sensor:
  - platform: cse7766
    current:
      name: Current
      accuracy_decimals: 1
    voltage:
      name: Voltage
      accuracy_decimals: 1
    power:
      name: Power
      accuracy_decimals: 1
      id: power
  - platform: total_daily_energy
    name: Energy
    power_id: power
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

binary_sensor:
  - platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: true
    id: button1
    filters:
      - delayed_on_off: 50ms
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 200ms
        then:
          - logger.log: Single-Click Detected
          - switch.toggle: relay1
      - timing:
          - ON for at most 400ms
          - OFF for at most 200ms
          - ON for at most 400ms
          - OFF for at least 200ms
        then:
          - logger.log: Double-Click Detected
          - homeassistant.service:
              service: input_boolean.toggle
              data:
                entity_id: input_boolean.${automation_name}
